// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT1CKRJ26OYGdZ7P0fpC8XuF2SGMfw_z8',
    appId: '1:218656007172:web:ebc1e4010abd7fd2fd0151',
    messagingSenderId: '218656007172',
    projectId: 'aidaily-2b873',
    authDomain: 'aidaily-2b873.firebaseapp.com',
    storageBucket: 'aidaily-2b873.firebasestorage.app',
    measurementId: 'G-N8JP0Q3MN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMvF_C4FJwBE4sFEQbpg_SK1roIQQN3EQ',
    appId: '1:218656007172:android:f200d75d3db47f61fd0151',
    messagingSenderId: '218656007172',
    projectId: 'aidaily-2b873',
    storageBucket: 'aidaily-2b873.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhxadKuYO3aZ-NODH6SXQwxMS8RI80nX8',
    appId: '1:218656007172:ios:2188813ee408a249fd0151',
    messagingSenderId: '218656007172',
    projectId: 'aidaily-2b873',
    storageBucket: 'aidaily-2b873.firebasestorage.app',
    iosBundleId: 'com.rya.aiDailyNews',
  );
}
